from pathlib import Path
import unittest

class TestExactTarget(unittest.TestCase):
    def test_8dzw_target(self):
        p = Path(__file__).resolve().parents[1] / "examples" / "nucleolin_rsvf" / "target_RSV_F_8DZW_484aa.fasta"
        seq = "".join(x.strip() for x in p.read_text().splitlines() if x.strip() and not x.startswith(">"))
        self.assertEqual(len(seq), 484)
        self.assertEqual(seq, "QNITEEFYQSTCSAVSKGYLSALRTGWYTSVITIELSNIKENKCNGTDAKVKLIKQELDKYKNAVTELQLLMQSTPAANNRARRELPRFMNYTLNNAKKTNVTLSKKRKRRFLGFLLGVGSAIASGVAVCKVLHLEGEVNKIKSALLSTNKAVVSLSNGVSVLTFKVLDLKNYIDKQLLPIVNKQSCSISNIETVIEFQQKNNRLLEITREFSVNAGVTTPVSTYMLTNSELLSLINDMPITNDQKKLMSNNVQIVRQQSYSIMCIIKEEVLAYVVQLPLYGVIDTPCWKLHTSPLCTTNTKEGSNICLTRTDRGWYCDNAGSVSFFPQAETCKVQSNRVFCDTMNSLTLPSEVNLCNVDIFNPKYDCKIMTSKTDVSSSVITSLGAIVSCYGKTKCTASNKNRGIIKTFSNGCDYVSNKGVDTVSVGNTLYYVNKQEGKSLYVKGEPIINFYDPLVFPSDEFDASISQVNEKINQSLAFIRKS")

if __name__ == "__main__":
    unittest.main()
